name: 自动清理Action运行记录
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      # 官方一键安装gh
      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install gh -y

      - name: 批量删除旧运行记录
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 直接删除7天前记录，gh自动识别token，无需auth login
          gh run list --status completed,failure,cancelled --created "<7d" --limit 50 \
            --json databaseId -q '.[].databaseId' | xargs -I {} gh run delete {}
